city_mapping = {
            "Великий Новгород": "v_novgorod",
            "Нижний Тагил": "ntagil",
            "Верхняя Тура": "verhnyaya-tura",
            "Вышний Волочёк": "vyshnij-volochyok",
            "Мариинский Посад": "mariinskij-posad",
            "Горячий Ключ": "goryachij-klyuch",
            "Дагестанские Огни": "dagestanskie-ogni",
            "Западная Двина": "zapadnaya-dvina",
            "Красный Кут": "krasnyj-kut",
            "Красный Сулин": "krasnyj-sulin",
            "Красный Холм": "krasnyj-holm",
            "Лодейное Поле": "lodejnoe-pole",
            "Набережные Челны": "nabchelny",
            "Нижний Ломов": "nizhnij-lomov",
            "Нижний Новгород": "n_novgorod",
            "Новая Ладога": "novaya-ladoga",
            "Новая Ляля": "novaya-lyalya",
            "Новый Оскол": "novyj-oskol",
            "Старый Оскол": "staroskol",
            "Новый Уренгой": "n_urengoy",
            "Полярные Зори": "polyarnye-zori",
            "Сосновый Бор": "sosnovyj-bor",
            "Старая Купавна": "staraya-kupavna",
            "Старая Русса": "staraya-russa",
            "Старый Крым": "staryj-krym",
            "Спасск-Дальний": "spassk-dalnij",
            "Санкт-Петербург": "spb",
            "Южно-Сахалинск": "yuzhnosakhalinsk",
            "Петропавловск-Камчатский": "p_kamchatskiy",
            "Орехово-Зуево": "o_zuevo",
            "Ханты-Мансийск": "kh_mansiysk",
            
            "Грозный": "grozny"
        }