city_mapping = {
    "Алейск": "alejsk",
    "Александров": "aleksandrov",
    "Александровск": "aleksandrovsk",
    "Александровск-Сахалинский": "aleksandrovsk-sahalinskij",
    "Адыгейск": "adygejsk",
    "Аксай": "aksaj",
    "Алзамай": "alzamaj",
    "Альметьевск": "almetevsk",
    "Арсеньев": "arsenev",
    "Артём": "artem",
    "Артёмовский": "artyomovskij",
    "Асбест": "asbest",
    "Ахтубинск": "ahtubinsk",
    "Байкальск": "bajkalsk",
    "Баймак": "bajmak",
    "Балахна": "balahna",
    "Балей": "balej",
    "Балтийск": "baltijsk",
    "Бахчисарай": "bahchisaraj",
    "Бежецк": "bezheck",
    "Белая Холуница": "belaya-holunica",
    "Белебей": "belebej",
    "Белёв": "belyov",
    "Белинский": "belinskij",
    "Белогорск": "belogorsk-crimea",
    "Белогорск Амурская область": "belogorsk-amur-region",
    "Белогорск Республика Крым": "belogorsk-crimea",
    "Белокуриха": "belokuriha",
    "Белоозёрский": "beloozyorskij",
    "Белорецк": "beloreck",
    "Белоярский": "beloyarskij",
    "Белый": "belyj",
    "Берёзовский": "beryozovskij",
    "Берёзовский Свердловская область": "berezovskij",
    "Берёзовский Кемеровская область": "beryozovskij",
    "Благодарный": "blagodarnyj",
    "Богородицк": "bogorodick",
    "Бодайбо": "bodajbo",
    "Болгар": "bolgar",
    "Болотное": "bolotnoe",
    "Болохово": "bolohovo",
    "Болхов": "bolhov",
    "Большой Камень": "bolshoj-kamen",
    "Бронницы": "bronnicy",
    "Будённовск": "budyonnovsk",
    "Буй": "buj",
    "Буйнакск": "bujnaksk",
    "Валдай": "valdaj",
    "Валуйки": "valujki",
    "Великий Новгород": "v_novgorod",
    "Великий Устюг": "velikij-ustyug",
    "Венёв": "venyov",
    "Верхнеуральск": "verhneuralsk",
    "Верхний Тагил": "verhnij-tagil",
    "Верхний Уфалей": "verhnij-ufalej",
    "Верхняя Пышма": "verhnyaya-pyshma",
    "Верхняя Салда": "verhnyaya-salda",
    "Верхняя Тура": "verhnyaya-tura",
    "Верхотурье": "verhoture",
    "Весьегонск": "vesegonsk",
    "Видное": "vdn",
    "Вилюйск": "vilyujsk",
    "Вихоревка": "vihorevka",
    "Волхов": "volhov",
    "Высоцк": "vysock",
    "Вышний Волочёк": "vyshnij-volochyok",
    "Вяземский": "vyazemskij",
    "Гай": "gaj",
    "Гвардейск": "gvardejsk",
    "Голицыно": "golicyno",
    "Горно-Алтайск": "gornoaltaysk",
    "Горняк": "gornyak",
    "Городец": "gorodec",
    "Городище": "gorodishche",
    "Гороховец": "gorohovec",
    "Горячий Ключ": "goryachij-klyuch",
    "Грайворон": "grajvoron",
    "Грязи": "gryazi",
    "Грязовец": "gryazovec",
    "Губаха": "gubaha",
    "Губкинский": "gubkinskij",
    "Гурьевск": "gurevsk-kemerovo-region",
    "Гурьевск Калининградская область": "gurevsk-kaliningrad-region",
    "Гурьевск Кемеровская область": "gurevsk-kemerovo-region",
    "Гусиноозёрск": "gusinoozyorsk",
    "Дагестанские Огни": "dagestanskie-ogni",
    "Джанкой": "dzhankoj",
    "Дзержинский": "dzerzhinskij",
    "Дно": "dno",
    "Донецк": "doneck",
    "Донской": "donskoj",
    "Духовщина": "duhovshchina",
    "Дюртюли": "dyurtyuli",
    "Евпатория": "evpatoriya",
    "Егорьевск": "egorevsk",
    "Ейск": "ejsk",
    "Екатеринбург": "ekaterinburg",
    "Елабуга": "elabuga",
    "Елец": "elec",
    "Ельня": "elnya",
    "Еманжелинск": "emanzhelinsk",
    "Енисейск": "enisejsk",
    "Железногорск": "zheleznogorsk-krasnoyarsk-region",
    "Железногорск Красноярский край": "zheleznogorsk-krasnoyarsk-region",
    "Железногорск Курская область": "zheleznogorsk-kursk-region",
    "Железногорск-Илимский": "zheleznogorsk-ilimskij",
    "Жигулёвск": "zhigulevsk",
    "Жуковский": "zhukovskiy",
    "Заволжье": "zavolzhe",
    "Заозёрный": "zaozyornyj",
    "Заозёрск": "zaozyorsk",
    "Западная Двина": "zapadnaya-dvina",
    "Заполярный": "zapolyarnyj",
    "Зарайск": "zarajsk",
    "Заречный": "zarechnyj-penza-region",
    "Заречный Свердловская область": "zarechnyj-sverdlovsk-region",
    "Заречный Пензенская область": "zarechnyj-penza-region",
    "Зима": "zima",
    "Зубцов": "zubcov",
    "Изобильный": "izobilnyj",
    "Иланский": "ilanskij",
    "Ишимбай": "ishimbaj",
    "Йошкар-Ола": "yoshkarola",
    "Калач-на-Дону": "kalach-na-donu",
    "Каменск-Уральский": "k_uralskiy",
    "Каменск-Шахтинский": "kamensk-shahtinskij",
    "Камень-на-Оби": "kamen-na-obi",
    "Каргат": "kargat",
    "Катайск": "katajsk",
    "Кедровый": "kedrovyj",
    "Кирово-Чепецк": "kirovo-chepeck",
    "Кировск": "kirovsk-leningrad-region",
    "Кировск Мурманская область": "kirovsk-murmansk-region",
    "Кировск Ленинградская область": "kirovsk-leningrad-region",
    "Кирс": "kirs",
    "Клин": "klin",
    "Клинцы": "klincy",
    "Кола": "kola",
    "Коммунар": "kommunar",
    "Короча": "korocha",
    "Кохма": "kohma",
    "Копейск": "kopeysk",
    "Красноармейск": "krasnoarmejsk-saratov-region",
    "Красноармейск Московская область": "krasnoarmejsk-moscow-region",
    "Красноармейск Саратовская область": "krasnoarmejsk-saratov-region",
    "Краснознаменск": "krasnoznamensk-moscow-region",
    "Краснознаменск Калининградская область": "krasnoznamensk-kaliningrad-region",
    "Краснознаменск Московская область": "krasnoznamensk-moscow-region",
    "Краснослободск": "krasnoslobodsk-volgograd-region",
    "Краснослободск Мордовия": "krasnoslobodsk-mordovia-region",
    "Краснослободск Волгоградская область": "krasnoslobodsk-volgograd-region",
    "Кремёнки": "kremyonki",
    "Красный Кут": "krasnyj-kut",
    "Красный Сулин": "krasnyj-sulin",
    "Красный Холм": "krasnyj-holm",
    "Кубинка": "kubinka",
    "Кузнецк": "kuzneck",
    "Курган": "kurgan",
    "Курчалой": "kurchaloj",
    "Кушва": "kushva",
    "Кяхта": "kyahta",
    "Лахденпохья": "lahdenpohya",
    "Ленинск-Кузнецкий": "leninsk-kuzneckij",
    "Лесной": "lesnoj",
    "Лихославль": "lihoslavl",
    "Лодейное Поле": "lodejnoe-pole",
    "Лосино-Петровский": "losino-petrovskij",
    "Луга": "luga",
    "Луза": "luza",
    "Луховицы": "luhovicy",
    "Любим": "lyubim",
    "Майкоп": "maikop",
    "Майский": "majskij",
    "Макарьев": "makarev",
    "Малоархангельск": "maloarhangelsk",
    "Малоярославец": "maloyaroslavec",
    "Мариинский Посад": "mariinskij-posad",
    "Маркс": "marks",
    "Медвежьегорск": "medvezhegorsk",
    "Межгорье": "mezhgore",
    "Мирный": "mirnyj-arkhangelsk-region",
    "Мирный Республика Саха": "mirnyj-yakutia-region",
    "Мирный Архангельская область": "mirnyj-arkhangelsk-region",
    "Михайлов": "mihajlov",
    "Михайловка": "mihajlovka",
    "Михайловск": "mihajlovsk",
    "Михайловск Ставропольский край": "mikhaylovsk",
    "Михайловск Свердловская область": "mihajlovsk",
    "Можайск": "mozhajsk",
    "Муром": "murom",
    "Мценск": "mcensk",
    "Набережные Челны": "nabchelny",
    "Находка": "nahodka",
    "Нижние Серги": "nizhnie-sergi",
    "Нижний Ломов": "nizhnij-lomov",
    "Нижний Новгород": "n_novgorod",
    "Нижний Тагил": "ntagil",
    "Николаевск-на-Амуре": "nikolaevsk-na-amure",
    "Никольск": "nikolsk-vologda-region",
    "Никольск Пензенская область": "nikolsk-penza-region",
    "Никольск Вологодская область": "nikolsk-vologda-region",
    "Никольское": "nikolskoe",
    "Новая Ляля": "novaya-lyalya",
    "Новоалтайск": "novoaltajsk",
    "Новоаннинский": "novoanninskij",
    "Новокуйбышевск": "novokujbyshevsk",
    "Новотроицк": "novotroick",
    "Новохопёрск": "novohopyorsk",
    "Новый Оскол": "novyj-oskol",
    "Новый Уренгой": "n_urengoy",
    "Облучье": "obluche",
    "Озёры": "ozyory",
    "Октябрьский": "oktyabrskij",
    "Олёкминск": "olyokminsk",
    "Олонец": "olonec",
    "Орёл": "orel",
    "Орехово-Зуево": "o_zuevo",
    "Оса": "osa",
    "Остров": "ostrov",
    "Островной": "ostrovnoj",
    "Отрадное": "otradnoe",
    "Отрадный": "otradnyj",
    "Оха": "oha",
    "Оханск": "ohansk",
    "Очёр": "ochyor",
    "Павловский Посад": "pavlovskij-posad",
    "Первомайск": "pervomajsk",
    "Перевоз": "perevoz",
    "Переславль-Залесский": "pereslavl-zalesskij",
    "Пермь": "perm",
    "Петровск-Забайкальский": "petrovsk-zabajkalskij",
    "Петропавловск-Камчатский": "p_kamchatskiy",
    "Петухово": "petuhovo",
    "Петушки": "petushki",
    "Пионерский": "pionerskij",
    "Питкяранта": "pitkyaranta",
    "Подпорожье": "podporozhe",
    "Покачи": "pokachi",
    "Покров": "pokrov",
    "Полевской": "polevskoj",
    "Полысаево": "polysaevo",
    "Полярные Зори": "polyarnye-zori",
    "Полярный": "polyarnyj",
    "Поронайск": "poronajsk",
    "Порхов": "porhov",
    "Похвистнево": "pohvistnevo",
    "Пошехонье": "poshekhone",
    "Приморск": "primorsk-kaliningrad-region",
    "Приморск Ленинградская область": "primorsk-leningrad-region",
    "Приморск Калининградская область": "primorsk-kaliningrad-region",
    "Приморско-Ахтарск": "primorsko-ahtarsk",
    "Прокопьевск": "prokopevsk",
    "Прохладный": "prohladnyj",
    "Пугачёв": "pugachyov",
    "Пустошка": "pustoshka",
    "Пыть-Ях": "pyt-yah",
    "Радужный": "raduzhnyj-vladimir-region",
    "Радужный Владимирская область": "raduzhnyj-vladimir-region",
    "Радужный Ханты-Мансийский АО": "raduzhnyj-hanty-mansijsk-region",
    "Райчихинск": "rajchihinsk",
    "Раменское": "ramenskoe",
    "Реж": "rezh",
    "Родники": "rodniki",
    "Ростов Великий": "rostov-yaroslavl-region",
    "Санкт-Петербург": "spb",
    "Светлый": "svetlyj",
    "Свободный": "svobodnyj",
    "Северобайкальск": "severobajkalsk",
    "Сельцо": "selco",
    "Сенгилей": "sengilej",
    "Серпухов": "serpuhov",
    "Сибай": "sibaj",
    "Славянск-на-Кубани": "slavyansk-na-kubani",
    "Сланцы": "slancy",
    "Слободской": "slobodskoj",
    "Советск": "sovetsk-kaliningrad-region",
    "Советск Калининградская область": "sovetsk-kaliningrad-region",
    "Советск Кировская область": "sovetsk-kirov-region",
    "Советск Тульская область": "sovetsk-tula-region",
    "Советский": "sovetskij",
    "Сокол": "sokol",
    "Соль-Илецк": "sol-ileck",
    "Сольцы": "solcy",
    "Сосенский": "sosenskij",
    "Сосновый Бор": "sosnovyj-bor",
    "Спасск-Дальний": "spassk-dalnij",
    "Спасск-Рязанский": "spassk-ryazanskij",
    "Старая Купавна": "staraya-kupavna",
    "Старица": "starica",
    "Старый Крым": "staryj-krym",
    "Старый Оскол": "staroskol",
    "Стрежевой": "strezhevoj",
    "Строитель": "stroitel",
    "Судак": "sudak",
    "Суджа": "sudzha",
    "Сураж": "surazh",
    "Сухиничи": "suhinichi",
    "Сухой Лог": "suhoj-log",
    "Сычёвка": "sychyovka",
    "Тайга": "tajga",
    "Тайшет": "tajshet",
    "Талица": "talica",
    "Тихвин": "tihvin",
    "Тихорецк": "tihoreck",
    "Тольятти": "tolyatti",
    "Топки": "topki",
    "Торопец": "toropec",
    "Трёхгорный": "tryohgornyj",
    "Троицк": "troick",
    "Тейково": "tejkovo",
    "Тольятти": "togliatti",
    "Туймазы": "tujmazy",
    "Удачный": "udachnyj",
    "Узловая": "uzlovaya",
    "Улан-Удэ": "ulanude",
    "Урай": "uraj",
    "Усолье-Сибирское": "usole-sibirskoe",
    "Усолье": "usole",
    "Феодосия": "feodosiya",
    "Фокино": "fokino-bryansk-region",
    "Хадыженск": "hadyzhensk",
    "Ханты-Мансийск": "kh_mansiysk",
    "Харабали": "harabali",
    "Харовск": "harovsk",
    "Хвалынск": "hvalynsk",
    "Хилок": "hilok",
    "Холм": "holm",
    "Холмск": "holmsk",
    "Хотьково": "hotkovo",
    "Цивильск": "civilsk",
    "Цимлянск": "cimlyansk",
    "Циолковский": "ciolkovskij",
    "Чайковский": "chajkovskij",
    "Черемхово": "cheremhovo",
    "Чёрмоз": "chyormoz",
    "Черняховск": "chernyahovsk",
    "Чудово": "chudovo",
    "Чусовой": "chusovoj",
    "Чухлома": "chuhloma",
    "Шали": "shali",
    "Шахты": "shakhty",
    "Шахунья": "shahunja",
    "Шацк": "shack",
    "Шелковская": "shełkovskaya",
    "Шумиха": "shumiha",
    "Щёкино": "shchekino",
    "Щёлкино": "shchyolkino",
    "Щучье": "shchuche",
    "Электрогорск": "ehlektrogorsk",
    "Электроугли": "elektrougli",
    "Эртиль": "ehrtil",
    "Южно-Сахалинск": "yuzhnosakhalinsk",
    "Южно-Сухокумск": "yuzhno-suhokumsk",
    "Юрьев-Польский": "yurev-polskij",
    "Юрьевец": "yurevec",
    "Юхнов": "yuhnov",
    "Яровое": "yarovoe",
    "Ярцево": "yarcevo",
    "Ясный": "yasnyj",
    "Яхрома": "yahroma"
}